### ISSUE TITLE
[PE-D][Tester B] UG: Unclear how to edit platform

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W14-3/tp#151]
I noticed that in the boxes, there are some texts such as no platform released, or platforms released 1.

![image.png](https://raw.githubusercontent.com/potty10/ped/main/files/8cfba7f5-89d9-4444-b11e-e6133a9e1082.png)

It was not stated anywhere in the UG how to update this field.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: potty10/ped#7

**Comment by clevon-w** [comment]
platforms / ug issue
