### ISSUE TITLE
[PE-D][Tester A] Inconsistency in [a/APPLICANT]... and [a/APPLICANTS...] in User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W14-3/tp#163]
![image.png](https://raw.githubusercontent.com/gwynethguo/ped/main/files/32948cdb-aee0-48c6-b125-97d678327145.png)

![image.png](https://raw.githubusercontent.com/gwynethguo/ped/main/files/9670cb93-fd49-4497-bf1d-72f7e4ceb145.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: gwynethguo/ped#11

**Comment by clevon-w** [comment]
i assume this person meant we are missing some "existing v" in edit and add
